### ISSUE TITLE
Bare comment option for upstate throws error

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/nci_scripts#24]
Using `uqstat` just with `--comment` option throws an error:
```
$ /g/data/hh5/public/apps/nci_scripts/uqstat --comment
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'comment'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/g/data/hh5/public/apps/nci_scripts/uqstat", line 223, in <module>
    main()
  File "/g/data/hh5/public/apps/nci_scripts/uqstat", line 206, in main
    table = table.join(df['comment'])
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.07/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2893, in get_loc
    raise KeyError(key) from err
KeyError: 'comment'
```

Works fine if there is another option before or after it, e.g.
```
$ /g/data/hh5/public/apps/nci_scripts/uqstat --comment -P v45
```

**Comment by ScottWales** [comment]
Error is because no comments are available. Have now provided a default of 'None'
